import { Inter } from 'next/font/google';
import './globals.css';
import Footer from '@/app/components/Footer';
import { AppContextProvider } from '@/app/contexts/AppContext';

import { CharContextProvider } from '@/app/contexts/CharContext'

import Navbar from '@/app/components/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <CharContextProvider>
        <AppContextProvider>
          <Navbar />
          {children}
          <Footer />
        </AppContextProvider>
        </CharContextProvider>
      </body>
    </html>
  );
}
